Ui/Pci.CvBuilder.UI/Areas/Common/Controllers/ExperienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Pci.CommonLib.EFRepositories.Model;
using Pci.CvBuilder.UI.UIServiceWorker.PageSW;
using Pci.CvBuilder.UI.UIServiceWorker.ExperienceSW;
using Pci.CvBuilder.Entity;

namespace Pci.CvBuilder.UI.Areas.Common.Controllers
{
    public class ExperienceController : Controller
    {
        // GET: Common/Experience
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Read data for gridview
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            long id = Convert.ToInt32(this.Session["Id"]);
            var listData = new ExperienceServiceWorker().GetExperienceList().Where(o => o.UserId == id).ToList();
            return Json(listData.ToDataSourceResult(request));
        }

        /// <summary>
        /// Detail 
        /// </summary>
        /// <returns></returns>
        public ActionResult Detail()
        {
            Experience experience = new Experience();
            return View(experience);
        }

        /// <summary>
        /// Update view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Update(int id)
        {
            Experience experience = new Experience();
            experience = new PageServiceWorker().GetDetailData<Experience>(id);
            return View(experience);
        }

        /// <summary>
        /// View detail
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult View(int id)
        {
            Experience experience = new Experience();
            experience = new PageServiceWorker().GetDetailData<Experience>(id);
            return View(experience);
        }

        /// <summary>
        /// Create Experience
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(Experience request)
        {
            try
            {
                var userId = this.Session["Id"].ToString();

                Experience experience = new Experience();
                experience.UserId = int.Parse(userId);
                experience.Company = request.Company;
                experience.JobTitle = request.JobTitle;
                experience.JobDescription = request.JobDescription;
                experience.StartDate = request.StartDate;
                experience.EndDate = request.EndDate;
                experience.StillWorking = request.StillWorking;
                //experience.StillWorking = request.StillWorking.Substring(0,1);
                experience.Salary = request.Salary;

                new ExperienceServiceWorker().CreateExperience(experience);
                return Json(new { success = true });
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Update Experience
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateData(Experience request)
        {
            try
            {
                var userId = this.Session["Id"].ToString();
                Experience experience = new Experience();
                experience.Id = request.Id;
                experience.UserId = int.Parse(userId);
                experience.Company = request.Company;
                experience.JobTitle = request.JobTitle;
                experience.JobDescription = request.JobDescription;
                experience.StartDate = request.StartDate;
                experience.EndDate = request.EndDate;
                experience.StillWorking = request.StillWorking;
                //experience.StillWorking = request.StillWorking.Substring(0,1);
                experience.Salary = request.Salary;

                new ExperienceServiceWorker().UpdateExperience(experience);
                return Json(new { success = true });
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Delete data
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Destroy(int id)
        {
            try
            {
                Experience experience = new Experience();
                experience = new PageServiceWorker().GetDetailData<Experience>(id);

                new ExperienceServiceWorker().DeleteExperience(experience);
                return Json(new { success = true });
            }
            catch
            {
                throw;
            }
        }


    }
}

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Experience/Detail.cshtml
@model Pci.CvBuilder.Entity.Experience
@using Kendo.Mvc.UI


@using (Ajax.BeginForm("Create", "Experience",
    new AjaxOptions
    {
        UpdateTargetId = "DetailDiv",
        OnBegin = "onDetailBegin",
        OnSuccess = "onDetailResult",
        OnFailure = "onDetailFailure",
        HttpMethod = "Post"
    },
    new { id = "DetailForm" }
    ))
{
    
    <div id="DetailDiv"></div>

    <div class="editor-label">Company</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Company, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("Company")
    </div>

    <div class="editor-label">Job Tittle</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.JobTitle, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("JobTitle")
    </div>

    <div class="editor-label">Job Description</div>
    <div class="editor-field">
        @Html.TextAreaFor(model => model.JobDescription, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("JobDescription")
    </div>

    <div class="editor-label">Start Date</div>
    <div class="editor-field">
        @(Html.Kendo().DatePickerFor(model => model.StartDate)
        .Name("StartDate")
        .Value(DateTime.Today)
        .HtmlAttributes(new { style = "width: 93%" })
        )
    </div>

    <div class="editor-label">End Date</div>
    <div class="editor-field">
        @(Html.Kendo().DatePickerFor(model => model.EndDate)
        .Name("EndDate")
        .Value(DateTime.Today)
        .HtmlAttributes(new { style = "width: 93%" })
        )
    </div>

    <div class="editor-label">Still Working</div>
        <div class="editor-field">
            @(Html.Kendo().DropDownListFor(model => model.StillWorking)
                                .HtmlAttributes(new { style = "width:200px" })
                        //.Name("authStatus")
                        .BindTo(new List<string>()
                        {
                            "No",
                            "Yes"
                        })
                        .SelectedIndex(0)
            )
    </div>

    <div class="editor-label">Salary</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Salary, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox"})
        @Html.ValidationMessage("Salary")
    </div>


    <table>
        <tr>
            <td style="width: 125px"></td>
            <td>
                <div>
                    <button id="SaveButton" type="submit" value="Create" class='k-button k-button-icontext'><span class='k-icon k-update'></span>Save</button>
                </div>
            </td>
        </tr>
    </table>
}

<script type="text/javascript">
    $(document).ready(function () {
        $.validator.setDefaults({
            ignore: ""
        });

        $("#Salary").kendoNumericTextBox({
            decimals: 2
        });

        $('#DetailForm').validate({
            rules: {
                Company: {
                    required: true,
                },
                JobTitle: {
                    required: true
                },
                JobDescription: {
                    required: true,
                },
                StartDate: {
                    required: true,
                },
                EndDate: {
                    required: true
                },
                StillWorking: {
                    required: true,
                }
            }

        });
        $("#Company").focusout(function () {
            $('#DetailForm').validate().element("#Company");
        });
        $("#JobTitle").focusout(function () {
            $('#DetailForm').validate().element("#JobTitle");
        });
        $("#JobDescription").focusout(function () {
            $('#DetailForm').validate().element("#JobDescription");
        });
        $("#StartDate").focusout(function () {
            $('#DetailForm').validate().element("#StartDate");
        });
        $("#EndDate").focusout(function () {
            $('#DetailForm').validate().element("#EndDate");
        });
        $("#StillWorking").focusout(function () {
            $('#DetailForm').validate().element("#StillWorking");
        });
        $("#Salary").focusout(function () {
            $('#DetailForm').validate().element("#Salary");
        });
    });

    function onDetailBegin() {
        //  $("#DetailDiv").showSpinner(true);
    }

    function onDetailResult(result) {
        if (result.success) {
            alert("Data Created Successfully");
            $("#window").data("kendoWindow").close();
            $('#Grid').data('kendoGrid').dataSource.read();
            $('#Grid').data('kendoGrid').refresh();
        } else {
            alert(result.error);
        }
    }

    function onDetailFailure(error) {
        //  $("#DetailDiv").showSpinner(false);
    }
</script>

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Experience/Index.cshtml
@model IEnumerable<Pci.CvBuilder.Entity.Experience>
@using Kendo.Mvc.UI
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="captionForm">Experience</h3>
@(Html.Kendo().Window()
        .Name("window")
        .Title("Experience")
        .Modal(true)
        .Width(400)
        .Actions(actions => actions.Maximize().Close())
        .Visible(false)
        .Draggable(true)
)

@(Html.Kendo().Grid(Model)
    .Name("Grid")
        .HtmlAttributes(new { Style = "height:460px" })
    .Columns(columns =>
    {
        columns.Bound(p => p.Company).Width(150);
        columns.Bound(p => p.JobTitle).Width(150);
        columns.Bound(p => p.JobDescription).Width(150);
        columns.Bound(p => p.StartDate).Width(150).Format("{0:dd/MM/yyyy}");
        columns.Bound(p => p.EndDate).Width(150).Format("{0:dd/MM/yyyy}");
        columns.Bound(p => p.StillWorking).Width(150);
        columns.Bound(p => p.Salary).Width(150);

        columns.Command(command =>
        {
            command.Custom("viewDetails").Click("viewDetails").Text("View");
            command.Custom("updateDetails").Click("updateDetails").Text("Edit");
            command.Custom("deleteDetails").Click("deleteDetails").Text("Delete");
        }).Width(300);
    })
    .ToolBar(toolbar =>
            {
                toolbar.Template(
                    @<text>
                        <button id="Add_Experience" type="button" value="AddUser" class='k-button k-button-icontext'>Add</button>
                    </text>);
            })
    .Pageable(pager => pager.Input(true).Refresh(true).Numeric(false)
    .PageSizes(new[] { 50, 100, 200 }))
    .Filterable()
    .Scrollable()
    .Events(e => e.DataBound("dataBound"))
    .Resizable(resize => resize.Columns(true))
    .ColumnMenu()
    .Sortable()
        .Editable(editable => editable.Mode(GridEditMode.PopUp).TemplateName("Update"))
    .DataSource(dataSource => dataSource
        .Ajax().ServerOperation(true)
        .PageSize(50)
        .Model(model =>
        {
            model.Id(p => p.Id);
        })
        .Read(read => read.Action("Read", "Experience"))
        )
)

<script type="text/javascript">
    function viewDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dialog = $("#window").data("kendoWindow");
        dialog.refresh({
            url: "View",
            data: { id: dataItem.id }
        });
        dialog.center().open();
    };

    function updateDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dialog = $("#window").data("kendoWindow");
        dialog.refresh({
            url: "Update",
            data: { id: dataItem.id }
        });
        dialog.center().open();
    };

    function deleteDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var confirmation = confirm("Are you sure you want to delete this data?");
        if (confirmation == true) {
            $.ajax({
                type: "POST",
                url: "Destroy",
                data: { id: dataItem.id },
                success: function (e) {
                    if (e.success) {
                        alert("Data Deleted Successfully");
                        $("#Grid").data("kendoGrid").dataSource.read();
                    }
                    else {
                        alert("Error! Can't Delete Data!");
                    }
                }
            });
        }
        else
        {
            return false;
        }
    };

    function onDetailBegin() {
        kendo.ui.progress($("#DetailDiv"), true);
    }

    $(document).ready(function () {


        $("#Add_Experience").click(function () {
            var dialog = $("#window").data("kendoWindow");
            dialog.refresh({
                url: "Detail"
            });

            dialog.center();
            dialog.open();
        });
    });

    function dataBound() {
        var grid = $("#Grid").data("kendoGrid");

        var dataSource = grid.dataSource;
        if (this.dataSource.view().length == 0) {
            //insert empty row
            var colspan = this.thead.find("th").length;
            var emptyRow = "<tr><td colspan='" + colspan + "'></td></tr>";
            this.tbody.html(emptyRow);
        }

        var state = {
            columns: grid.columns,
            page: dataSource.page(),
            pageSize: dataSource.pageSize(),
            sort: dataSource.sort(),
            filter: dataSource.filter(),
            group: dataSource.group()
        };

        $.ajax({
            url: "~/Experience/Index",
            data: {
                data: JSON.stringify(state)
            }
        });
    }

</script>

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Experience/Update.cshtml
@model Pci.CvBuilder.Entity.Experience
@using Kendo.Mvc.UI


@using (Ajax.BeginForm("UpdateData", "Experience",
    new AjaxOptions
    {
        UpdateTargetId = "DetailUpdateDiv",
        OnBegin = "onDetailBegin",
        OnSuccess = "onDetailResult",
        OnFailure = "onDetailFailure",
        HttpMethod = "Post"
    },
    new { id = "DetailForm" }
    ))
{
    <div id="DetailUpdateDiv"></div>

    <div class="editor-label">Company</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Company, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("Company")
    </div>

    <div class="editor-label">Job Tittle</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.JobTitle, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("JobTitle")
    </div>

    <div class="editor-label">Job Description</div>
    <div class="editor-field">
        @Html.TextAreaFor(model => model.JobDescription, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("JobDescription")
    </div>

    <div class="editor-label">Start Date</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.StartDate, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessageFor(model => model.StartDate)
    </div>

    <div class="editor-label">End Date</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.EndDate, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessageFor(model => model.EndDate)
    </div>

    <div class="editor-label">Still Working</div>
    <div class="editor-field">
        @(Html.Kendo().DropDownListFor(model => model.StillWorking)
                                .HtmlAttributes(new { style = "width:200px" })
                        .BindTo(new List<string>()
                        {
                            "No",
                            "Yes"
                        })
                        .SelectedIndex(0)
        )
    </div>

    <div class="editor-label">Salary</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Salary, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox", @type = "number" })
        @Html.ValidationMessage("Salary")
    </div>
    @Html.HiddenFor(model => model.Id)

    <table>
        <tr>
            <td style="width: 125px"></td>
            <td>
                <div>
                    <button id="SaveButton" type="submit" value="Update" class='k-button k-button-icontext'><span class='k-icon k-update'></span>Update</button>
                </div>
            </td>
        </tr>
    </table>
}

<script type="text/javascript">
    $(document).ready(function () {

        $("#StartDate").kendoDatePicker();
        $("#EndDate").kendoDatePicker();

        $.validator.setDefaults({
            ignore: ""
        });

        $("#Salary").kendoNumericTextBox({
            decimals: 2
        });

        $('#DetailForm').validate({
            rules: {
                Company: {
                    required: true,
                },
                JobTitle: {
                    required: true
                },
                JobDescription: {
                    required: true,
                },
                StartDate: {
                    required: true,
                },
                EndDate: {
                    required: true
                },
                StillWorking: {
                    required: true,
                }
            }

        });
        $("#Company").focusout(function () {
            $('#DetailForm').validate().element("#Company");
        });
        $("#JobTitle").focusout(function () {
            $('#DetailForm').validate().element("#JobTitle");
        });
        $("#JobDescription").focusout(function () {
            $('#DetailForm').validate().element("#JobDescription");
        });
        $("#StartDate").focusout(function () {
            $('#DetailForm').validate().element("#StartDate");
        });
        $("#EndDate").focusout(function () {
            $('#DetailForm').validate().element("#EndDate");
        });
        $("#StillWorking").focusout(function () {
            $('#DetailForm').validate().element("#StillWorking");
        });
        $("#Salary").focusout(function () {
            $('#DetailForm').validate().element("#Salary");
        });
    });

    function onDetailBegin() {
        //  $("#DetailDiv").showSpinner(true);
    }

    function onDetailResult(result) {
        if (result.success) {
            alert("Data Update Successfully");
            $("#window").data("kendoWindow").close();
            $('#Grid').data('kendoGrid').dataSource.read();
            $('#Grid').data('kendoGrid').refresh();
        } else {
            alert(result.error);
        }
    }

    function onDetailFailure(error) {
        //  $("#DetailDiv").showSpinner(false);
    }
</script>

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Experience/View.cshtml
@model Pci.CvBuilder.Entity.Experience
@using Kendo.Mvc.UI


@using (Ajax.BeginForm("View", "Experience",
    new AjaxOptions
    {
        UpdateTargetId = "DetailUpdateDiv",
        OnBegin = "onDetailBegin",
        OnSuccess = "onDetailResult",
        OnFailure = "onDetailFailure",
        HttpMethod = "Post"
    },
    new { id = "DetailForm" }
    ))
{
    <div id="DetailUpdateDiv"></div>

    <div class="editor-label">Company</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Company, (object)new
        {
            @readonly = "readonly",
            style = " background-color: #F2F2F2;",
            autocomplete = "off",
            @class = "k-textbox"
        })
        @Html.ValidationMessageFor(model => model.Company)
    </div>

    <div class="editor-label">Job Title</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.JobTitle, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.JobTitle)
    </div>

    <div class="editor-label">Job Description</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.JobDescription, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.JobDescription)
    </div>

    <div class="editor-label">Start Date</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.StartDate, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.StartDate)
    </div>

    <div class="editor-label">EndDate</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.EndDate, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.EndDate)
    </div>

    <div class="editor-label">Still Working</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.StillWorking, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.StillWorking)
    </div>

    <div class="editor-label">Salary</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Salary, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.Salary)
    </div>
    @Html.HiddenFor(model => model.Id)
}