Ui/Pci.CvBuilder.UI/Areas/Common/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Pci.CommonLib.EFRepositories.Model;
using Pci.CvBuilder.UI.UIServiceWorker.PageSW;
using Pci.CvBuilder.UI.UIServiceWorker.DocumentSW;
using Pci.CvBuilder.Entity;
using System.IO;

namespace Pci.CvBuilder.UI.Areas.Common.Controllers
{
    public class DocumentController : Controller
    {
        // GET: Common/Document
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Read data for gridview
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            long id = Convert.ToInt32(this.Session["Id"]);
            var listData = new DocumentServiceWorker().GetDocumentList().Where(o=>o.UserId ==id).ToList();
            return Json(listData.ToDataSourceResult(request));
        }

        /// <summary>
        /// Detail Document
        /// </summary>
        /// <returns></returns>
        public ActionResult Detail()
        {
            Document document = new Document();
            return View(document);
        }

        /// <summary>
        /// Update document
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Update(int id)
        {
            Document document = new Document();
            document = new PageServiceWorker().GetDetailData<Document>(id);
            return View(document);
        }

        /// <summary>
        /// View Document
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult View(int id)
        {
            Document document = new Document();
            document = new PageServiceWorker().GetDetailData<Document>(id);
            return View(document);
        }

        /// <summary>
        /// Create Document
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Create(HttpPostedFileBase files, Document request)
        {
            try
            {
                if (files != null && files.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(files.FileName);

                    // check extension file
                    if (Path.GetExtension(fileName).ToLower() != ".pdf")
                    {
                        @ViewBag.Message = "File is not .PDF type.";
                    }
                    else
                    {
                        var physicalPath = Path.Combine(Server.MapPath("~/Content/Images/Document"), fileName);
                        files.SaveAs(physicalPath);

                        var userId = this.Session["Id"].ToString();

                        Document document = new Document();
                        document.UserId = int.Parse(userId);
                        document.DocumentType = request.DocumentType;
                        document.DocumentName = files.FileName;

                        new DocumentServiceWorker().CreateDocument(document);

                        @ViewBag.Message = "Success upload file";
                    }
                }
                else
                {
                    @ViewBag.Message = "Failed upload file";
                }
            }
            catch (Exception ex)
            {
                @ViewBag.Message = "ERROR:" + ex.Message.ToString();
            }
            return View("Index");
        }

        /// <summary>
        /// Update Document
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        [AllowAnonymous]
        public ActionResult UpdateData(HttpPostedFileBase files, Document request)
        {
            try
            {
                if (files != null && files.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(files.FileName);

                    // check extension file
                    if (Path.GetExtension(fileName).ToLower() != ".pdf")
                    {
                        @ViewBag.Message = "File is not .PDF type.";
                    }
                    else
                    {
                        var physicalPath = Path.Combine(Server.MapPath("~/Content/Images/Document"), fileName);
                        files.SaveAs(physicalPath);

                        var userId = this.Session["Id"].ToString();

                        Document document = new Document();
                        document.Id = request.Id;
                        document.UserId = int.Parse(userId);
                        document.DocumentType = request.DocumentType;
                        document.DocumentName = files.FileName;

                        new DocumentServiceWorker().UpdateDocument(document);
                        @ViewBag.Message = "Success upload file";
                    }
                }
                else
                {
                    @ViewBag.Message = "Failed upload file";
                }
            }
            catch (Exception ex)
            {
                @ViewBag.Message = "ERROR:" + ex.Message.ToString();
            }
            return View("Index");
        }

        public ActionResult Destroy(int id)
        {
            try
            {
                Document document = new Document();
                document = new PageServiceWorker().GetDetailData<Document>(id);

                new DocumentServiceWorker().DeleteDocument(document);
                return Json(new { success = true });
            }
            catch { throw; }
        }
    }
}

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Document/Detail.cshtml
@model Pci.CvBuilder.Entity.Document
@using Kendo.Mvc.UI

@using (Html.BeginForm("Create", "Document", FormMethod.Post,
                         new { enctype = "multipart/form-data" }))
{

    <div class="editor-label">Document Type</div>
    <div class="editor-field">
        @(Html.Kendo().DropDownListFor(model => model.DocumentType)
                                .HtmlAttributes(new { style = "width:200px" })
                        .BindTo(new List<string>()
                        {
                            "Identity Card (KTP)",
                            "Ijazah",
                            "Transcripts",
                            "Certificate"
                        })
                        .SelectedIndex(0)
        )
    </div>

    <div class="editor-label">Document Name</div>
    <div class="editor-field">
                    <br />
                    @ViewBag.Message
                    <br />
                    <input type="file" name="files" id="files" />
                    <div class="demo-hint"><strong>*PDF</strong></div>
    </div>

    <table>
        <tr>
            <td style="width: 125px"></td>
            <td>
                <div>
                    <button id="SaveButton" type="submit" value="Create" class='k-button k-button-icontext'><span class='k-icon k-update'></span>Save</button>
                </div>
            </td>
        </tr>
    </table>

}

<script type="text/javascript">
    $(document).ready(function() {

    });
</script>

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Document/Index.cshtml
@model IEnumerable<Pci.CvBuilder.Entity.Document>
@using Kendo.Mvc.UI
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="captionForm">Document</h3>
@(Html.Kendo().Window()
        .Name("windowView")
        .Title("Document")
        .Modal(true)
        .Width(600)
        .Height(600)
        .Actions(actions => actions.Maximize().Close())
        .Visible(false)
        .Draggable(true)
)

@(Html.Kendo().Window()
        .Name("windowEdit")
        .Title("Document")
        .Modal(true)
        .Width(400)
        .Actions(actions => actions.Maximize().Close())
        .Visible(false)
        .Draggable(true)
)

@(Html.Kendo().Grid(Model)
    .Name("Grid")
        .HtmlAttributes(new { Style = "height:460px" })
    .Columns(columns =>
    {
        columns.Bound(p => p.DocumentType).Width(150);
        columns.Bound(p => p.DocumentName).Width(150);

        columns.Command(command =>
        {
            command.Custom("viewDetails").Click("viewDetails").Text("View");
            command.Custom("updateDetails").Click("updateDetails").Text("Edit");
            command.Custom("deleteDetails").Click("deleteDetails").Text("Delete");
        }).Width(300);
    })
    .ToolBar(toolbar =>
            {
                toolbar.Template(
                    @<text>
                        <button id="Add_Document" type="button" value="AddDocument" class='k-button k-button-icontext'>Add</button>
                    </text>);
            })
    .Pageable(pager => pager.Input(true).Refresh(true).Numeric(false)
    .PageSizes(new[] { 50, 100, 200 }))
    .Filterable()
    .Scrollable()
    .Events(e => e.DataBound("dataBound"))
    .Resizable(resize => resize.Columns(true))
    .ColumnMenu()
    .Sortable()
    .Editable(editable => editable.Mode(GridEditMode.PopUp).TemplateName("Update"))
    .DataSource(dataSource => dataSource
        .Ajax().ServerOperation(true)
        .PageSize(50)
        .Model(model =>
        {
            model.Id(p => p.Id);
        })
        .Read(read => read.Action("Read", "Document"))
        )
)

@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <script type="text/javascript">
        alert("@ViewBag.Message");
    </script>
}

<script type="text/javascript">
    function viewDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dialog = $("#windowView").data("kendoWindow");
        dialog.refresh({
            url: "View",
            data: { id: dataItem.id }
        });
        dialog.center().open();
    };

    function updateDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dialog = $("#windowEdit").data("kendoWindow");
        dialog.refresh({
            url: "Update",
            data: { id: dataItem.id }
        });
        dialog.center().open();
    };

    function deleteDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var confirmation = confirm("Are you sure you want to delete this data?");
        if (confirmation == true) {
            $.ajax({
                type: "POST",
                url: "Destroy",
                data: { id: dataItem.id },
                success: function (e) {
                    if (e.success) {
                        alert("Data Deleted Successfully");
                        $("#Grid").data("kendoGrid").dataSource.read();
                    }
                    else {
                        alert("Error! Can't Delete Data!");
                    }
                }
            });
        }
        else
        {
            return false;
        }
    };

    function onDetailBegin() {
        kendo.ui.progress($("#DetailDiv"), true);
    }

    $(document).ready(function () {


        $("#Add_Document").click(function () {
            var dialog = $("#windowEdit").data("kendoWindow");
            dialog.refresh({
                url: "Detail"
            });

            dialog.center();
            dialog.open();
        });
    });

    function dataBound() {
        var grid = $("#Grid").data("kendoGrid");

        var dataSource = grid.dataSource;
        if (this.dataSource.view().length == 0) {
            //insert empty row
            var colspan = this.thead.find("th").length;
            var emptyRow = "<tr><td colspan='" + colspan + "'></td></tr>";
            this.tbody.html(emptyRow);
        }

        var state = {
            columns: grid.columns,
            page: dataSource.page(),
            pageSize: dataSource.pageSize(),
            sort: dataSource.sort(),
            filter: dataSource.filter(),
            group: dataSource.group()
        };

        $.ajax({
            url: "~/Document/Index",
            data: {
                data: JSON.stringify(state)
            }
        });
    }

</script>

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Document/Update.cshtml
@model Pci.CvBuilder.Entity.Document
@using Kendo.Mvc.UI

@using (Html.BeginForm("UpdateData", "Document", FormMethod.Post,
                         new { enctype = "multipart/form-data" }))
{
    <div class="editor-label">Document Type</div>
    <div class="editor-field">
        @(Html.Kendo().DropDownListFor(model => model.DocumentType)
                                .HtmlAttributes(new { style = "width:200px" })
                        .BindTo(new List<string>()
                        {
                            "Identity Card (KTP)",
                            "Ijazah",
                            "Transcripts",
                            "Certificate"
                        })
                        .SelectedIndex(0)
        )
    </div>

    <div class="editor-label">Document Name</div>
    <div class="editor-field">
        <br>
        @ViewBag.Message
        <br />
        <input type="file" name="files" id="files" />
        <div class="demo-hint"><strong>*PDF</strong></div>
    </div>
    @Html.HiddenFor(model => model.Id)

    <table>
        <tr>
            <td style="width: 125px"></td>
            <td>
                <div>
                    <button id="SaveButton" type="submit" value="Update" class='k-button k-button-icontext'><span class='k-icon k-update'></span>Update</button>
                </div>
            </td>
        </tr>
    </table>

}

<script type="text/javascript">
    $(document).ready(function() {

    });
</script>


Ui/Pci.CvBuilder.UI/Areas/Common/Views/Document/View.cshtml
@model Pci.CvBuilder.Entity.Document
@using Kendo.Mvc.UI


@using (Ajax.BeginForm("View", "Document",
    new AjaxOptions
    {
        UpdateTargetId = "DetailUpdateDiv",
        OnBegin = "onDetailBegin",
        OnSuccess = "onDetailResult",
        OnFailure = "onDetailFailure",
        HttpMethod = "Post"
    },
    new { id = "DetailForm" }
    ))
{
    <div id="DetailUpdateDiv"></div>

    <div class="editor-label">Document Type</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.DocumentType, (object)new
        {
            @readonly = "readonly",
            style = " background-color: #F2F2F2;",
            autocomplete = "off",
            @class = "k-textbox"
        })
        @Html.ValidationMessageFor(model => model.DocumentType)
    </div>

    <div class="editor-label">Document Name</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.DocumentName, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.DocumentName)
    </div>
    @Html.HiddenFor(model => model.Id)

    <object data="~/Content/Images/Document/@Model.DocumentName" type="application/pdf" width="550" height="450">
        <embed src="file:///Content/Images/Document/@Model.DocumentName" type="application/pdf" />
    </object>
}