Ui/Pci.CvBuilder.UI/Areas/Common/Controllers/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Pci.CommonLib.EFRepositories.Model;
using Pci.CvBuilder.UI.UIServiceWorker.PageSW;
using Pci.CvBuilder.UI.UIServiceWorker.TrainingSW;
using Pci.CvBuilder.Entity;


namespace Pci.CvBuilder.UI.Areas.Common.Controllers
{
    public class TrainingController : Controller
    {
        // GET: Common/Training
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Read data for gridview
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            long id = Convert.ToInt32(this.Session["Id"]);
            var listData = new TrainingServiceWorker().GetTrainingList().Where(o => o.UserId == id).ToList();
            return Json(listData.ToDataSourceResult(request));
        }

        /// <summary>
        /// Detail 
        /// </summary>
        /// <returns></returns>
        public ActionResult Detail()
        {
            Training training = new Training();
            return View(training);
        }

        /// <summary>
        /// Update view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Update(int id)
        {
            Training training = new Training();
            training = new PageServiceWorker().GetDetailData<Training>(id);
            return View(training);
        }

        /// <summary>
        /// View detail
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult View(int id)
        {
            Training training = new Training();
            training = new PageServiceWorker().GetDetailData<Training>(id);
            return View(training);
        }

        /// <summary>
        /// Create Training
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(Training request)
        {
            try
            {
                var userId = this.Session["Id"].ToString();

                Training training = new Training();
                training.UserId = int.Parse(userId);
                training.ProgramName = request.ProgramName;
                training.Institution = request.Institution;
                training.Date = request.Date;
                training.Certified = request.Certified;
                // sub string kalau databasenya nChar(1)
                //training.Certified = request.Certified.Substring(0,1);

                new TrainingServiceWorker().CreateTraining(training);
                return Json(new { success = true });
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Update Training
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateData(Training request)
        {
            try
            {
                var userId = this.Session["Id"].ToString();
                Training training = new Training();
                training.Id = request.Id;
                training.UserId = int.Parse(userId);
                training.ProgramName = request.ProgramName;
                training.Institution = request.Institution;
                training.Date = request.Date;
                training.Certified = request.Certified;
                //training.Certified = request.Certified.Substring(0,1);

                new TrainingServiceWorker().UpdateTraining(training);
                return Json(new { success = true });
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Delete data
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Destroy(int id)
        {
            try
            {
                Training training = new Training();
                training = new PageServiceWorker().GetDetailData<Training>(id);

                new TrainingServiceWorker().DeleteTraining(training);
                return Json(new { success = true });
            }
            catch
            {
                throw;
            }
        }

    }
}

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Training/Detail.cshtml
@model Pci.CvBuilder.Entity.Training
@using Kendo.Mvc.UI


@using (Ajax.BeginForm("Create", "Training",
    new AjaxOptions
    {
        UpdateTargetId = "DetailDiv",
        OnBegin = "onDetailBegin",
        OnSuccess = "onDetailResult",
        OnFailure = "onDetailFailure",
        HttpMethod = "Post"
    },
    new { id = "DetailForm" }
    ))
{

    <div id="DetailDiv"></div>

    <div class="editor-label">Program Name</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.ProgramName, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("ProgramName")
    </div>

    <div class="editor-label">Institution</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Institution, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("Institution")
    </div>

    <div class="editor-label">Date</div>
    <div class="editor-field">
        @(Html.Kendo().DatePickerFor(model => model.Date)
        .Name("Date")
        .Value(DateTime.Today)
        .HtmlAttributes(new { style = "width: 93%" })
        )
    </div>

    <div class="editor-label">Certified</div>
    <div class="editor-field">
        @(Html.Kendo().DropDownListFor(model => model.Certified)
                                .HtmlAttributes(new { style = "width:200px" })
                        .BindTo(new List<string>()
                        {
                            "No",
                            "Yes"
                        })
                        .SelectedIndex(0)
        )
    </div>

    <table>
        <tr>
            <td style="width: 125px"></td>
            <td>
                <div>
                    <button id="SaveButton" type="submit" value="Create" class='k-button k-button-icontext'><span class='k-icon k-update'></span>Save</button>
                </div>
            </td>
        </tr>
    </table>
}

<script type="text/javascript">
    $(document).ready(function () {
        $.validator.setDefaults({
            ignore: ""
        });

        $('#DetailForm').validate({
            rules: {
                ProgramName: {
                    required: true,
                },
                Institution: {
                    required: true,
                },
                Date: {
                    required: true,
                },
                Certified: {
                    required: true,
                }
            }
        });

        $("#ProgramName").focusout(function () {
            $('#DetailForm').validate().element("#ProgramName");
        });
        $("#Institution").focusout(function () {
            $('#DetailForm').validate().element("#Institution");
        });
        $("#Date").focusout(function () {
            $('#DetailForm').validate().element("#Date");
        });
        $("#Certified").focusout(function () {
            $('#DetailForm').validate().element("#Certified");
        });
    });
        function onDetailBegin() {
            //  $("#DetailDiv").showSpinner(true);
        }

        function onDetailResult(result) {
            if (result.success) {
                alert("Data Created Successfully");
                $("#window").data("kendoWindow").close();
                $('#Grid').data('kendoGrid').dataSource.read();
                $('#Grid').data('kendoGrid').refresh();
            } else {
                alert(result.error);
            }
        }

        function onDetailFailure(error) {
            //  $("#DetailDiv").showSpinner(false);
        }
        </script>

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Training/Index.cshtml
@model IEnumerable<Pci.CvBuilder.Entity.Training>
@using Kendo.Mvc.UI
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="captionForm">Training</h3>
@(Html.Kendo().Window()
        .Name("window")
        .Title("Training")
        .Modal(true)
        .Width(400)
        .Actions(actions => actions.Maximize().Close())
        .Visible(false)
        .Draggable(true)
)

@(Html.Kendo().Grid(Model)
    .Name("Grid")
        .HtmlAttributes(new { Style = "height:460px" })
    .Columns(columns =>
    {
        columns.Bound(p => p.ProgramName).Width(150);
        columns.Bound(p => p.Institution).Width(150);
        columns.Bound(p => p.Date).Width(150).Format("{0:dd/MM/yyyy}");
        columns.Bound(p => p.Certified).Width(150);

        columns.Command(command =>
            {
                command.Custom("viewDetails").Click("viewDetails").Text("View");
                command.Custom("updateDetails").Click("updateDetails").Text("Edit");
                command.Custom("deleteDetails").Click("deleteDetails").Text("Delete");
            }).Width(300);
    })
    .ToolBar(toolbar =>
            {
                toolbar.Template(
                    @<text>
                        <button id="Add_Training" type="button" value="AddUser" class='k-button k-button-icontext'>Add</button>
                    </text>);
            })
    .Pageable(pager => pager.Input(true).Refresh(true).Numeric(false)
    .PageSizes(new[] { 50, 100, 200 }))
    .Filterable()
    .Scrollable()
    .Events(e => e.DataBound("dataBound"))
    .Resizable(resize => resize.Columns(true))
    .ColumnMenu()
    .Sortable()
        .Editable(editable => editable.Mode(GridEditMode.PopUp).TemplateName("Update"))
    .DataSource(dataSource => dataSource
        .Ajax().ServerOperation(true)
        .PageSize(50)
        .Model(model =>
        {
            model.Id(p => p.Id);
        })
        .Read(read => read.Action("Read", "Training"))
        )
)

<script type="text/javascript">
    function viewDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dialog = $("#window").data("kendoWindow");
        dialog.refresh({
            url: "View",
            data: { id: dataItem.id }
        });
        dialog.center().open();
    };

    function updateDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dialog = $("#window").data("kendoWindow");
        dialog.refresh({
            url: "Update",
            data: { id: dataItem.id }
        });
        dialog.center().open();
    };

    function deleteDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var confirmation = confirm("Are you sure you want to delete this data?");
        if (confirmation == true) {
            $.ajax({
                type: "POST",
                url: "Destroy",
                data: { id: dataItem.id },
                success: function (e) {
                    if (e.success) {
                        alert("Data Deleted Successfully");
                        $("#Grid").data("kendoGrid").dataSource.read();
                    }
                    else {
                        alert("Error! Can't Delete Data!");
                    }
                }
            });
        }
        else
        {
            return false;
        }
    };

    function onDetailBegin() {
        kendo.ui.progress($("#DetailDiv"), true);
    }

    $(document).ready(function () {


        $("#Add_Training").click(function () {
            var dialog = $("#window").data("kendoWindow");
            dialog.refresh({
                url: "Detail"
            });

            dialog.center();
            dialog.open();
        });
    });

    function dataBound() {
        var grid = $("#Grid").data("kendoGrid");

        var dataSource = grid.dataSource;
        if (this.dataSource.view().length == 0) {
            //insert empty row
            var colspan = this.thead.find("th").length;
            var emptyRow = "<tr><td colspan='" + colspan + "'></td></tr>";
            this.tbody.html(emptyRow);
        }

        var state = {
            columns: grid.columns,
            page: dataSource.page(),
            pageSize: dataSource.pageSize(),
            sort: dataSource.sort(),
            filter: dataSource.filter(),
            group: dataSource.group()
        };

        $.ajax({
            url: "~/Training/Index",
            data: {
                data: JSON.stringify(state)
            }
        });
    }

</script>

Ui/Pci.CvBuilder.UI/Areas/Common/Views/Training/Update.cshtml
@model Pci.CvBuilder.Entity.Training
@using Kendo.Mvc.UI


@using (Ajax.BeginForm("UpdateData", "Training",
    new AjaxOptions
    {
        UpdateTargetId = "DetailUpdateDiv",
        OnBegin = "onDetailBegin",
        OnSuccess = "onDetailResult",
        OnFailure = "onDetailFailure",
        HttpMethod = "Post"
    },
    new { id = "DetailForm" }
    ))
{

    <div id="DetailUpdateDiv"></div>

    <div class="editor-label">Program Name</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.ProgramName, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("ProgramName")
    </div>

    <div class="editor-label">Institution</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Institution, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessage("Institution")
    </div>

    <div class="editor-label">Date</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Date, (object)new { autocomplete = "off", style = "width:200px", @class = "k-textbox" })
        @Html.ValidationMessageFor(model => model.Date)
    </div>

    <div class="editor-label">Certified</div>
    <div class="editor-field">
        @(Html.Kendo().DropDownListFor(model => model.Certified)
                                .HtmlAttributes(new { style = "width:200px" })
                        .BindTo(new List<string>()
                        {
                            "No",
                            "Yes"
                        })
                        .SelectedIndex(0)
        )
    </div>
    @Html.HiddenFor(model => model.Id)

    <table>
        <tr>
            <td style="width: 125px"></td>
            <td>
                <div>
                    <button id="SaveButton" type="submit" value="Update" class='k-button k-button-icontext'><span class='k-icon k-update'></span>Update</button>
                </div>
            </td>
        </tr>
    </table>
}

<script type="text/javascript">
    $(document).ready(function () {

        $("#Date").kendoDatePicker();

        $.validator.setDefaults({
            ignore: ""
        });

        $('#DetailForm').validate({
            rules: {
                ProgramName: {
                    required: true,
                },
                Institution: {
                    required: true,
                },
                Date: {
                    required: true,
                },
                Certified: {
                    required: true,
                }
            }
        });

        $("#ProgramName").focusout(function () {
            $('#DetailForm').validate().element("#ProgramName");
        });
        $("#Institution").focusout(function () {
            $('#DetailForm').validate().element("#Institution");
        });
        $("#Date").focusout(function () {
            $('#DetailForm').validate().element("#Date");
        });
        $("#Certified").focusout(function () {
            $('#DetailForm').validate().element("#Certified");
        });
    });
        function onDetailBegin() {
            //  $("#DetailDiv").showSpinner(true);
        }

        function onDetailResult(result) {
            if (result.success) {
                alert("Data Update Successfully");
                $("#window").data("kendoWindow").close();
                $('#Grid').data('kendoGrid').dataSource.read();
                $('#Grid').data('kendoGrid').refresh();
            } else {
                alert(result.error);
            }
        }

        function onDetailFailure(error) {
            //  $("#DetailDiv").showSpinner(false);
        }
</script>


Ui/Pci.CvBuilder.UI/Areas/Common/Views/Training/View.cshtml
@model Pci.CvBuilder.Entity.Training
@using Kendo.Mvc.UI


@using (Ajax.BeginForm("View", "Training",
    new AjaxOptions
    {
        UpdateTargetId = "DetailUpdateDiv",
        OnBegin = "onDetailBegin",
        OnSuccess = "onDetailResult",
        OnFailure = "onDetailFailure",
        HttpMethod = "Post"
    },
    new { id = "DetailForm" }
    ))
{
    <div id="DetailUpdateDiv"></div>

    <div class="editor-label">Program Name</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.ProgramName, (object)new
        {
            @readonly = "readonly",
            style = " background-color: #F2F2F2;",
            autocomplete = "off",
            @class = "k-textbox"
        })
        @Html.ValidationMessageFor(model => model.ProgramName)
    </div>

    <div class="editor-label">Institution</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Institution, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.Institution)
    </div>

    <div class="editor-label">Date</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Date, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.Date)
    </div>

    <div class="editor-label">Certified</div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Certified, (object)new
            {
                @readonly = "readonly",
                style = " background-color: #F2F2F2;",
                autocomplete = "off",
                @class = "k-textbox"
            })
        @Html.ValidationMessageFor(model => model.Certified)
    </div>
    @Html.HiddenFor(model => model.Id)
}

